---
name: Makefile (test catalog scripts)

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run make test for catalog scripts
        run: make -C scripts/catalog test-build-catalog-from-resources-template
